### ISSUE TITLE
Allow paragraphs in description

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#48] opened 2020-08-12 18:34 UTC
I'd like to be able to write several paragraphs in the description text. Double newline as separator i guess.

**Comment by quite** [comment] 2020-08-25 12:22
I notice that newlines can be entered, and are stored in the db. But display rendering removes them.

**Comment by rotsee** [comment] 2020-08-30 17:56
As the issue is with browsers stripping out white-space (as they should, by the html spec), I guess the most correct way to fix it would be with the [white-space](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space) CSS property `white-space: break-spaces`? Unless there are any unintentional side-effects of that?

**Comment by quite** [comment] 2020-08-31 05:19
Could be side effects that i dont think about... But looks good. We should probably trim whitespace from head and tail? Maybe that's done already? That is relevant for #52 too i think.

**Comment by rotsee** [comment] 2020-09-01 09:14
Fixed in https://github.com/fruktkartan/fruktkartan/commit/e1a4cbea79998d90863a8eb35aa7cf493da98347 and https://github.com/fruktkartan/fruktkartan/commit/f59be61300f0b36f70c9242f05a1bacfb49dbc69

**Closed by rotsee** 2020-09-01 09:14 UTC
