### ISSUE TITLE
Zoom in to a specific zoom level, when following a tree url

### ISSUE THREAD

**Issue by quite** [fruktkartan/fruktkartan#53] opened 2020-08-25 12:13 UTC
Typing or following a tree URL `/#/t/{ssm_key}` when already visiting Fruktkartan does not properly pan and zoom to the tree. Following such URL on a blank or other page does!

**Comment by quite** [comment] 2020-08-25 12:17
Hm... or sometimes it works, sometimes not.

**Comment by rotsee** [comment] 2020-08-25 12:51
I'll need some help to reproduce this (on my machine it seems to always work).
What browser? Any specific circumstances where it fails? Does in neither pan nor zoom?

**Comment by quite** [comment] 2020-08-25 13:16
It's so hard :) Chromium 84, incognito window to get rid of all my extensions.

- Go to the site
- By now, I see the whole country. I'm blocking location, could that interfere?
- Edit URL, adding `/t/2385746878`
- For me, that pops up some black currants, but neither pans nor zooms.

**Comment by rotsee** [comment] 2020-08-25 13:35
Ah, that's feature, not a bug :D

In this case the tree _is already in view_ (albeit very hard to make out....), so there is no need to zoom. 

We could change the behavior so that we always _zoom in_ to a specific zoom level, when panning to the tree. That would probably be less confusing.

**Comment by quite** [comment] 2020-08-25 15:47
Oh :facepalm:

**Comment by rotsee** [comment] 2020-08-30 17:41
Fixed in: https://github.com/fruktkartan/fruktkartan/commit/8e8cd0b94f8fe6e105e4f6650585ed371980e8b6

We will zoom in (but never zoom out) to a predefined zoom level whenever opening a tree.

**Comment by quite** [comment] 2020-08-31 06:03
Oh, this doesn't feel right at all. And sometimes ends up with the clicked tree *outside* of current map view, I think it would need to pan as well, but I have a feeling it will be hard to get right (and on various displays). I'll revert this. But open to possibly closing this until we get a better feel for what should be done...

**Comment by rotsee** [comment] 2020-08-31 07:02
> Oh, this doesn't feel right at all.

What about it feels wrong?

> And sometimes ends up with the clicked tree outside of current map view, I think it would need to pan as well, but I have a feeling it will be hard to get right (and on various displays).

This _should_ not be an issue, as we zoom in first, and then pan (panning happens whenever the view tree dialogue opens, in `adjustMapToTree()`). But maybe (I'm guessing now), the zoom animation sometimes doesn't have time to finish before we're panning into view?
The Leaflet map has a method `whenReady()` that seems to be intended for things like this, that I could look into!

(Another way around it could be to always move the tree to the _center_, rather than just moving it over the edge into the viewport.)

**Comment by quite** [comment] 2020-08-31 09:44
Yes, panning does not happen. I think it was only that which made it feel wrong :)

I thought about panning tree to center, but **only** if zoom actually changed. But I suggest to wait with that until we can see how timely panning feels.

**Comment by rotsee** [comment] 2020-09-01 18:51
This turns out to be surprisingly complex to get right; As we are changing the zoom level, a tree that was previously within the bounds of the map may end up outside them. In other words we don't know in advance exactly where to pan.

- First zooming, and then panning (after the zoom animation finished) is of course possible, but looks awkward.
- Calculating the desired zoom and position is possible, but much complexity for little profit.
- Doing it iteratively is heavy on the user's device, risks ending up in weird loops.

Furthermore: The current solution did not take the menu drawer into account. When panning to the right, the tree is sometimes hidden. Solving that bug would add another layer of complexity.

So, I'm suggesting a much, much simpler model: Whenever the tree view is opened, regardless of how, we pan to the tree. If we are far away, we'll zoom in at the same time. Could you have a look @quite, and merge if you find this solution acceptable? https://github.com/fruktkartan/fruktkartan/pull/54

**Comment by quite** [comment] 2020-09-01 19:00
I've just tried it out, and it works really well! Thanks a bunch for your thorough effort :)

**Comment by quite** [comment] 2020-09-01 19:01
The whole navigation felt snappier! Could that be...

**Closed** 2020-09-01 19:07 UTC
